# Generated by Django 2.2.10 on 2020-06-06 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'アイテム', 'verbose_name_plural': 'アイテム'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.IntegerField(choices=[(1, '男性'), (2, '女性'), (3, 'その他')], default=1, verbose_name='性別'),
        ),
    ]
